salesforce/kagekiri

- karma.conf.js
- package-lock.json
- package.json
- rollup.config.js
- test/test.js
`npm audit` complains about 2 moderate-severity vulnerabilities in `rollup-plugin-node-builtins`. It doesn't really affect us as it's just used in the build process, but it's a bit annoying so I'd prefer to get rid of it.
Once https://github.com/postcss/postcss-selector-parser/pull/210 is merged and published we won't need to do this, but for now we can just include our own `util` dependency to replace the node built-in one that `postcss-selector-parser` is relying on.
Incidentally we also use a built-in in our tests (`assert`), so this adds the `assert` package as well.
> fix: remove rollup-plugin-node-builtins

- src/index.js
- test/fixtures/attribute2/light.html
- test/fixtures/attribute2/shadow.html
- test/test.js
fixes #2
For attribute selectors, using `getAttribute()` and `hasAttribute()` is just a bit too fragile. As it turns out, there are lots of fancy [attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) and I don't want to code them all myself in JavaScript.
So we can just use the same strategy we already use for pseudo-selectors and just pass the attribute selector directly into `element.matches()`.
> fix: fix attribute selectors like ^= and *=

- karma.conf.js
- package-lock.json
- package.json
- rollup.config.js
- test/test.js
This reverts commit 745b2afc5c1eb1b4d68cf80d8f75aa4edda649a0.
Unfortunately it appears that #1 not only increased the size of our `iife.js` file from 172kB to 200kB, it also broke us in IE because of this issue: https://github.com/browserify/node-util/issues/40
Somehow that PR brought in `node-utils` which brought in [this code](https://github.com/browserify/node-util/blob/3c895410f1816110edeeb4c8e5427942ee97d65e/support/types.js#L24-L27) which throws an error in IE.
That PR only fixed two moderate-severity vulnerabilities in a devDependency, so in order to not break IE I think it's best to just revert.
> fix: Revert "fix: remove rollup-plugin-node-builtins (#1)"

- package.json
This info is missing on our npm page currently: https://www.npmjs.com/package/kagekiri
> fix: add git repo information to package.json

- karma.conf.js
- package-lock.json
- package.json
- rollup.config.js
- test/test.js
In some environments, having [this line from Buffer](https://github.com/feross/buffer/blob/5527ccae17dee95064a615c06a93014fc48c4072/index.js#L592) can cause runtime errors (e.g. because the Uint8Array prototype was modified to make its toString read-only).
Also, due to #5 we have to be careful in how we use Node builtins (such as Buffer) because of that particular bug that broke IE.
The easiest fix would be to wait for this PR (https://github.com/postcss/postcss-selector-parser/pull/210) to be merged, which would remove the Node builtins entirely from our one dependency, `postcss-selector-parser`. But that PR has been open for over a month, and I don't want us to be blocked on it.
So the easiest fix is:
1. Revive the old PR (#1) which removed the rollup-plugin-node-builtins, which `npm …
> fix: use fork of postcss-selector-parser, remove rollup-plugin-node-builtins

- package-lock.json
- package.json
Fixes a security vuln identified by `npm audit`.
> fix: update rollup-plugin-terser

- package-lock.json
- package.json
- rollup.config.js
I've noticed that, when using `kagekiri` as a dependency, bundlers like pika-pack may fail because of weirdness around `postcss-selector-parser`'s dependency on the built-in Node module `util` referenced by `util.promisify`.
There are arcane ways to fix this in your bundler, but then we're requiring all consumers of kagekiri to know how to do this for whatever bundler they're using (Rollup, Webpack, pika-pack, etc.). It's much simpler to just bundle `postcss-selector-parser` into all our output bundles, and to treat it as a `devDependency`.
> fix: bundle postcss-selector-parser into dist

- package.json
This tells bundlers that they can safely tree-shake the ES module output: https://webpack.js.org/guides/tree-shaking/
So for instance, consumers can use `querySelectorAll` without having to import code for `querySelector`.
> perf: add sideEffects: false

- package-lock.json
- package.json
- rollup.config.js
- src/index.js
Includes a global polyfill for `String.prototype.startsWith` and `String.prototype.endsWith`, which aren't supported in IE.
Normally I would prefer for a library not to bundle its own polyfills which modify global Objects, but this would be very tricky to fix with Babel/Buble in a non-global-touching way, especially since this usage comes from one of our dependencies (`postcss-selector-parser)`.
> fix: fix String startsWith/endsWith in IE

- .circleci/config.yml
- README.md
- package-lock.json
- package.json
The bundlesize is currently 52.57KB (most of which is `postcss-selector-parser`). I'd prefer for it not to get any larger than that, so this adds a CI test to ensure that it doesn't exceed 55kB.
> test: ensure bundle size does not grow

- test/fixtures/unusualSelectors1/light.html
- test/fixtures/unusualSelectors1/shadow.html
- test/test.js
These are just some tests to make sure that our CSS selector parser library works correctly in some unusual (but valid) cases, such as classes, IDs, and attributes containing unusual characters (quotes, double quotes, emoji, brackets, etc.).
> test: add tests for unusual CSS selectors

- src/index.js
I feel comfortable ignoring this code because I know it's IE-only. The other uncovered code still needs to be investigated.
> test: ignore IE-only code for coverage

- README.md
- karma.conf.js
- src/index.js
- test/getElementById.spec.js
- test/getElementsByClassName.spec.js
- test/getElementsByTagName.spec.js
- test/querySelector.spec.js
- test/utils.js
- types/kagekiri.d.ts
This PR adds `getElementById(id: string, context?: Node)`.
If the provided context is not a `Document`, `ShadowRoot` or `HTMLDocument` it will throw a TypeError
This PR also increases the coverage to 100% which allows us to set the threshold for 100%! 🥳
> feat: Get element by id

- types/kagekiri.d.ts
Adding the optional `context` argument.
> docs: fix typescript signature for getElementById

- README.md
- src/index.js
- test/matches.spec.js
- types/kagekiri.d.ts
With this PR we add support for a shadow piercing [`Element.matches()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches).
> feat: adding support for element.matches

- src/index.js
Cuts down a bit of duplicated code.
FWIW I also tested if it made sense to cache the result of `postcssSelectorParser()`, but in our whole test suite, running in Chrome on my MacBook, it consumed a sum total of ~3ms. So I don't think it's really worth it.
> fix: refactor to dedupe the AST code a bit

- .gitignore
- README.md
- package-lock.json
- package.json
- scripts/copy-typedoc-to-readme.js
- types/kagekiri.d.ts
Generates markdown API docs using `typedoc` (based on `kagekiri.d.ts`) and inserts them into the README. Makes it so we only have to update `kagekiri.d.ts` and the docs flow from there.
I didn't make it part of `npm run build` because it seems like something we'd only occasionally have to do, and it takes a bit of time to run.
> docs: generate API docs from typedoc, insert in README

- README.md
- src/index.js
- types/kagekiri.d.ts
> docs: rename `context` to `element` for `closest` and `matches`

- src/index.js
- test/getElementsByTagName.spec.js
- test/querySelector.spec.js
Fixes #57
Also added a test. For what it's worth, it looks like `document.getElementsByClassName`/`tagName`/etc. will also get the `<html>` node.
> fix: fix qS/qSA not returning <html>

- README.md
- package-lock.json
- package.json
- scripts/copy-typedoc-to-readme.js
- tsconfig.json
Updates `marked` to fix `npm audit`. Also that means we need to update `typedoc` and `typedoc-plugin-markdown`. Some minor breaking changes in here, but the TypeScript markdown docs are basically the same before and after.
> fix: update typedoc/marked

- .github/workflows/test.yml
- README.md
- karma.conf.js
- package-lock.json
- package.json
It's really annoying to run `test:debug` and see coverage-transformed files, so let's just have a special `test:coverage` command.
> test: do not run coverage tests by default

- package-lock.json
- package.json
I forgot about this particular bug: https://github.com/jlmakes/karma-rollup-preprocessor/issues/75
Downgrading this dep to 7.0.7 fixes the issue when running `npm run test:debug`.
> chore: downgrade karma-rollup-preprocessor to 7.0.7

- package-lock.json
- package.json
- scripts/bundlesize.mjs
`bundlesize` is deprecated and has heavy dependencies like `iltorb`; we can use a custom script instead with minimal dependencies.
> chore: remove bundlesize, use custom script

- package-lock.json
- package.json
- rollup.config.js
- src/index.js
Fixes #101
BREAKING CHANGE: drops support for IE11 and legacy browsers, consumers must supply their own polyfills/transforms
> fix: drop support for IE11 and legacy browsers
